---
- name: Install or Update Latest Terraform
  hosts: terraform
  become: True
  vars:
    program_dependencies:
     - curl
     - unzip
  pre_tasks:
  - name: install curl unzip on system
    ansible.builtin.package:
      name: "{{ program_dependencies }}"
      state: present

  tasks:
    - name: Get version number of latest terrafor release
      ansible.builtin.shell:
        cmd: curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | grep tag_name | cut  -d 'v' -f2 | tr -d \"\, 
      register: terraform_latest_release
      changed_when: false
      args:
        warn: no
    
    - set_fact:
        terraform_latest: "{{ terraform_latest_release.stdout }}"
      when:
        - terraform_latest_release.stdout is defined

    - name: check for existing terraform installation
      ansible.builtin.stat:
       path: "/usr/local/bin/terraform"
      register: current_terraform
      changed_when: false


    - name: Check current Terraform version if installed
      ansible.builtin.shell: /usr/local/bin/terraform --version | grep Terraform | cut  -d 'v' -f2 | tr -d \"\,
      register: current_terraform_version
      when: current_terraform.stat.exists
      changed_when: false
      failed_when: false


    - name: Install or update Terraform if needed
      block:
        - name: Download unarchive and move terraform to /usr/local/bin
          ansible.builtin.unarchive:
            src:  https://releases.hashicorp.com/terraform/{{terraform_latest}}/terraform_{{terraform_latest}}_linux_amd64.zip
            dest: /usr/local/bin/
            remote_src: yes
      when: 
       "not current_terraform.stat.exists or terraform_latest_release is not defined or terraform_latest_release|string not in current_terraform_version.stdout"
