---
# install_terraform project by Johan Sörell december 2021
# Project url: https://github.com/J-SirL/install_terraform/
# install_terraform project is a Terraform installer that installs latest Terraform using Ansible
# This project started because I needed a fast way to check for new terraform versions, 
# and got annoyed by all manual installation HowTo's so I decided to put it up for others to use. 
# It's very simple just clone the repository and run ansible-playbook install_or_update_terraform.yml and you have terraform on your system.

- name: Install or Update Latest Terraform
  hosts: terraform # Change to all if you do not want to add a [terraform] group in your inventory
  become: True
  vars:
    program_dependencies:
     - curl
     - unzip
  pre_tasks:
  - name: install curl unzip on system
    ansible.builtin.package:
      name: "{{ program_dependencies }}"
      state: present

  tasks:
    # Check the current version of terraform from hashicorp git repository 
    - name: Get version number of latest terrafor release
      ansible.builtin.shell:
        cmd: curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | grep tag_name | cut  -d 'v' -f2 | tr -d \"\, 
      register: terraform_latest_release
      changed_when: false
      args:
        warn: no

    # set the variable terraform_latest
    - set_fact:
        terraform_latest: "{{ terraform_latest_release.stdout }}"
      when:
        - terraform_latest_release.stdout is defined

    # check if there is an existing terraform installation
    - name: check for existing terraform installation
      ansible.builtin.stat:
       path: "/usr/local/bin/terraform"
      register: current_terraform
      changed_when: false

    # If terraform is installed check version
    - name: Check current Terraform version if installed
      ansible.builtin.shell: /usr/local/bin/terraform --version | grep Terraform | cut  -d 'v' -f2 | tr -d \"\,
      register: current_terraform_version
      when: current_terraform.stat.exists
      changed_when: false
      failed_when: false

    # Download unzip and move terraform to /usr/local/bin/ 
    - name: Install or update Terraform if needed
      block:
        - name: Download unarchive and move terraform to /usr/local/bin
          ansible.builtin.unarchive:
            src:  https://releases.hashicorp.com/terraform/{{terraform_latest}}/terraform_{{terraform_latest}}_linux_amd64.zip
            dest: /usr/local/bin/
            remote_src: yes
      when: 
       "not current_terraform.stat.exists or terraform_latest_release is not defined or terraform_latest_release|string not in current_terraform_version.stdout"

